import { Black_Ops_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toast } from "@heroui/react";

const BlackOpsOne = Black_Ops_One({
  subsets: ["latin"],
   weight: "400",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${BlackOpsOne.className}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <Toast.Provider />
        <main className="mx-auto container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
